title: 'Links'
name: 'Links'
author: 'Priyanshu Tiwari'
logo: 'https://raw.githubusercontent.com/ahampriyanshu/blog/main/assets/images/logo.png'
favicon: 'https://raw.githubusercontent.com/ahampriyanshu/blog/main/assets/images/favicon.ico'
tagline: 'Grouping all my projects, courses, articles in one place'
description: 'Grouping all my projects, courses, articles in one place'
url: https://links.ahampriyanshu.com
lang: en
timezone: Asia/Kolkata 
theme: jekyll-theme-hacker
rss-description: 'Grouping all my projects, courses, articles in one place'
plugins:
  - jekyll-sitemap  
  - jekyll-seo-tag
  - jekyll-feed