title: 'Priyanshu Tiwari'
name: 'Priyanshu Tiwari'
author: 'Priyanshu Tiwari'
logo: 'https://github.com/ahampriyanshu/blog/raw/main/assets/images/logo.png'
favicon: 'https://github.com/ahampriyanshu/blog/raw/main/assets/images/favicon.ico'
tagline: 'Simple static site to group all my projects, courses, articles, etc. in one place.'
description: 'Simple static site to group all my projects, courses, articles, etc. in one place.'
url: https://links.ahampriyanshu.com
lang: en
timezone: Asia/Kolkata 
theme: jekyll-theme-slate
rss-description: 'Simple static site to group all my projects, courses, articles, etc. in one place.'

plugins:
  - jekyll-sitemap  
  - jekyll-seo-tag
  - jekyll-feed